/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_andryyu_ndk_jni_JNIDemo */

#ifndef _Included_com_andryyu_ndk_jni_JNIDemo
#define _Included_com_andryyu_ndk_jni_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_andryyu_ndk_jni_JNIDemo
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_andryyu_ndk_jni_JNIDemo_getStringFromNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
